language: android
dist: trusty
sudo: required

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19
    - sys-img-armeabi-v7a-android-19

before_install:
    - yes | sdkmanager "platforms;android-28"
    - yes | sdkmanager "build-tools;28.0.3"


script:
  # connectedStagingDebugAndroidTest => run instrumentation tests
  # testDebugUnitTest => run unit tests on core
  # testStagingDebugUnitTest => run unit tests on project
  # jacocoTestReport => generate jacoco test report
  - ./gradlew testDebugUnitTest

env:
  matrix:
    - ANDROID_SDKS=android-19,sysimg-19 ANDROID_TARGET=android-19  ANDROID_ABI=armeabi-v7a